# Generated by Django 4.2.13 on 2024-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=255, verbose_name='date')),
                ('restaurant', models.CharField(max_length=255, verbose_name='restaurant')),
                ('planned_hours', models.IntegerField(default=0, verbose_name='planned hours')),
                ('hours_variance', models.FloatField(default=0, verbose_name='hours variance')),
                ('actual_hours', models.IntegerField(default=0, verbose_name='actual hours')),
                ('budget', models.FloatField(default=0, verbose_name='budget')),
                ('sells', models.FloatField(default=0, verbose_name='sells')),
                ('budget_variance', models.FloatField(default=0, verbose_name='budget variance')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
            },
        ),
    ]
